### ISSUE TITLE
Link in Figure 1

### ISSUE THREAD

**Issue by haudiobe** [Dash-Industry-Forum/ATSC#1]
Even though it is described, there is no links between service signaling and cache  in below figure (Figure 1). 

Kent will address

**Comment by chazlo** [comment]
05/20/16: addressed comment per proposed text changes to Sec. 2.3.4 as shown in TG3-6-XXXr0-DASH-IF-TV-Profile-v0_45+CL

**Comment by haudiobe** [comment]
Addressed in v0.50
