### ISSUE TITLE
Ad Insertion API

### ISSUE THREAD

**Issue by haudiobe** [Dash-Industry-Forum/ATSC#10]
Ad Insertion APIs
(Alex) generates sequence of operation

Alex/Mark/Charles

**Comment by ZmGorynych** [comment]
1. Client receives message indicating an upcoming ad break. This can be in MPD (XLink or event) or in segment (`emsg`)
2. Client requests ad decision. It may be handled locally (on device),  or may further go over broadband. Local handling does not preclude the handler communicating (e.g. using SCTE 130) with the ADS.
3. ADS responds with a sequence of zero or more ads.
4. Client plays the ad content.
5. Client reports ad playback.

**Comment by haudiobe** [comment]
needs more work
