### ISSUE TITLE
Bootstrapping

### ISSUE THREAD

**Issue by haudiobe** [Dash-Industry-Forum/ATSC#3]
1.	Upon the start of the scheduled program or section of a service, the receiver platform activates the DASH Player via IF-2, causing the DASH Player to request Media Segments from the HTTP proxy, via IF-4, at or after  Media Segment availability start times..
2.	DASH Player sends Segment request/receives Segments to/from the HTTP proxy/cache over IF-4. ROUTE receiver may stream MDE(s) over IF-4.

Shouldn’t this happen upon selection of a service, not the start of a program?
How about broadband case?
Need to add some for broadband case.
What is ROUTE receiver here?

Charles/Sejin

**Comment by chazlo** [comment]
05/20/16: addressed comment per proposed text changes to Sec. 2.3.4 as shown in TG3-6-XXXr0-DASH-IF-TV-Profile-v0_45+CL

**Comment by haudiobe** [comment]
Added to v0.50
