### ISSUE TITLE
Interactivity Specification ATSC

### ISSUE THREAD

**Issue by haudiobe** [Dash-Industry-Forum/ATSC#31]
A/337 is mentioned in 5.6.1, but do not have a reference. It seems to be a working draft, but we not have any information. Please fix.

**Comment by mikedo** [comment]
See: http://atsc.org/candidate-standard/a337-atsc-candidate-standard-application-signaling/ 
Note that this is under development.

**Comment by mikedo** [comment]
See also: http://atsc.org/candidate-standard/a344-atsc-candidate-standard-atsc-3-0-interactive-content/
