### ISSUE TITLE
[ATSC] 6.3.1 Clarify the usage for SCTE-35

### ISSUE THREAD

**Issue by haudiobe** [Dash-Industry-Forum/ATSC#33]
The following sentence is unclear, especially what is normative: "With that said, service offering may contain inband ‘emsg’ boxes or/and EventStream elements, carrying payloads such as SCTE 35 cue messages. Treatment of these events is outside the scope of this document, and the client is expected to be able to play seamlessly irrespective of whether the above events were handled by an application." 

Please clarify or remove.

**Comment by mikedo** [comment]
ATSC has previously communicated that SCTE 35 messages were not supported.  Propose it be deleted.
