### ISSUE TITLE
[ATSC] v1.0 References need updating

### ISSUE THREAD

**Issue by mikedo** [Dash-Industry-Forum/ATSC#36]
ATSC, ISO, and W3C references are out of date. And, some remain work in process today.

**Comment by mikedo** [comment]
A number of normative references are MPEG work in process. Although ATSC members have access (Category A Liaison to JTC1/SC29), non-MPEG-non-ATSC members will not. Additionally, some work is early and could easily change.

**Comment by haudiobe** [comment]
address this in v1.1 adding the latest references
