### ISSUE TITLE
v1.0 4.2.1 broadcast URLs must be relative

### ISSUE THREAD

**Issue by mikedo** [Dash-Industry-Forum/ATSC#37]
The text:

"The MPD Base URL's for broadcast resources are identified by using a relative reference per RFC3986 [28], where the first character in the URI is a "/"."

provides non-relative-URL constraint (leading "/").  RTR:

"The MPD Base URL's for broadcast resources are identified by using a relative reference per RFC3986 [28], where the first character in the URI cannot be a "/" or ".."."

**Comment by haudiobe** [comment]
agreed - add to v1.1

**Comment by haudiobe** [comment]
addressed in v1.01
