### ISSUE TITLE
[ATSC] v1.0, 4.3.1 Segment Timeline

### ISSUE THREAD

**Issue by mikedo** [Dash-Industry-Forum/ATSC#38]
4.3.1 says “The open ended Segment Timeline with @r=-1 should be used.”

However, an “open ended” Segment Timeline only works if all the Media Segments in the Period (or all the remaining Media Segments) are of equal duration. Let’s say they’re all 2.002 seconds long (because non-integer frame rate video is used), except the last one, which is shorter to force a Period to start at a certain UTC clock time or to force the Period to be an exact number of seconds. Assume for this example timescale=90000 and the Period wants to be exactly forty minutes long (00:40:00.0). Then instead of:

```
<SegmentTimeline>
<S t="0" d="180180" r=-1/> 
</SegmentTimeline>

```
  I think you’d have to define it like this: 

```
<SegmentTimeline> 
<S t="0" d="180180" r=1197/> 
<S d="144360"/> 
</SegmentTimeline>

```
The statement “@r=-1 should be used” is really a recommendation that Periods shouldn’t be settable to an integral number of seconds when using fractional frame-rate video. Or that the last Segment in a Period shouldn’t be able to be shorter than the others. I don’t think we want to say that. I suggest removing the statement recommending the open ended Segment Timeline.

**Comment by haudiobe** [comment]
Provide explanation on the usage of r=-1 and r>=0 in order to operate at live edge and different segment durations. More explanation and recommendation necessary => Thomas will check and work with Mark on this.

**Comment by ZmGorynych** [comment]
IMO, r=-1 makes sense while the duration of the last segment is not known. At the first MPD update when the last segment duration is known we can replace -1 with 1197 and add an extra S element.

**Comment by eyerm** [comment]
Alex,

True, though this way of operation would be atypical. For the vast majority of programming, the timing of Period boundaries is well known in advance and part of the precise playout schedule. I would be fine if the example included exactly the words you used: “If the duration of the last segment is not known” then r=-1 may be specified until an updated MPD establishes the duration of all segments in the Period.

Best regards,

Mark

**Comment by haudiobe** [comment]
Proposed update:
The open-ended Segment Timeline with @r=-1 should be used _describing the Segments at the live edge. This enables that Segments of the same duration may be distributed without updating the MPD and that a Segment is announced before its duration is known. For clarification purpose, this does not imply that Segments need to be of the same duration, Segments not at the live edge can be described by properly by the Segment Timeline in a causal fashion._
