### ISSUE TITLE
[ATSC] 1.0 IOP reference version in body text is incorrect

### ISSUE THREAD

**Issue by mikedo** [Dash-Industry-Forum/ATSC#41]
In 3.3 and 5.3.2.8, reference is made to IOP v3.3 [1]. It presumably should be v4.0, which is correct in the References section.  Best to delete versions from the body text.

**Comment by haudiobe** [comment]
Take out version from body => agree => v1.1

**Comment by haudiobe** [comment]
addressed in v1.01
