### ISSUE TITLE
[ATSC] 1.0 misc xrefs are incorrect

### ISSUE THREAD

**Issue by mikedo** [Dash-Industry-Forum/ATSC#42]
5.6.1 Xrefs to [6] are incorrect. Change to [5].
5.3.2.7 Xrefs to [7] are incorrect. Change to [6].
5.3.2.3 Xref to [10] in Table 2 caption is incorrect. Change to [16].
6.5.1 Xref to [12] is incorrect. Change to [11].
2.8.4.3 Xref to [18] s incorrect. Change to [20].

**Comment by haudiobe** [comment]
agree => v1.1

**Comment by haudiobe** [comment]
addressed in v1.01
