### ISSUE TITLE
[ATSC] some references are incorrect

### ISSUE THREAD

**Issue by mikedo** [Dash-Industry-Forum/ATSC#44]
In Table CCC

@minBufferTime 	O 	specifies a common duration used in the definition of the Representation data rate (see @bandwidth attribute in 5.3.5.2 and 5.3.5.4). 

Problem (aside from the odd table numbering):  the references 5.3.5.2 and 5.3.5.4 appear to be wrong because they need to have “of [2]” added (the references are to MPEG DASH, not this document).

This sort of problem occurs other places as well:  the pieces cut/pasted from 23009-1 need “of [2]” added here for context.

**Comment by haudiobe** [comment]
agreed => v1.1

**Comment by haudiobe** [comment]
addressed in v1.01.
