### ISSUE TITLE
[ATSC] misc editorial comments

### ISSUE THREAD

**Issue by mikedo** [Dash-Industry-Forum/ATSC#45]
See attached.
[TG3-6-084r0-MiscellaneousEditorialCommentsATSCProfile-v1.0.zip](https://github.com/Dash-Industry-Forum/ATSC/files/1115633/TG3-6-084r0-MiscellaneousEditorialCommentsATSCProfile-v1.0.zip)

**Comment by haudiobe** [comment]
addressed in v1.01
[Editorial-Comments-res.docx](https://github.com/Dash-Industry-Forum/ATSC/files/1329723/Editorial-Comments-res.docx)
