### ISSUE TITLE
[ATSC] HDR Signaling

### ISSUE THREAD

**Issue by mikedo** [Dash-Industry-Forum/ATSC#49]
In the present version of the DASH-IF IOP for ATSC 3.0, there is no provision for signaling high dynamic range.

Include signaling in the MPD for the transfer function; specifically SDR, PQ and HLG.  See Table 7.1 in A/341 https://www.atsc.org/wp-content/uploads/2017/05/A341-2017-Video-HEVC.pdf

**Comment by haudiobe** [comment]
Use Codec independent code points for this purpose aligned with DASH-IF IOP.

For HLG this needs more discussion as it is unclear if and how this relates. Is it related to what DVB does for DASH. We need to understand the detailed requirement: backward-compatible or not?

**Comment by ZmGorynych** [comment]
We need to make sure it is understood whether the backwards compatibility is to BT.709 or BT.2020.

**Comment by haudiobe** [comment]
For HDR video with the HLG transfer characteristics, the following constraints apply:
According to the above spec

- • Each SPS shall have colour_description_present_flag set equal to 1. This indicates that the colour_primaries, transfer_characteristics, and matrix_coeffs elements are present.
- • Each SPS shall have colour_primaries present and set equal to 9. This constrains the color primaries to ITU-R BT.2100 [23].
- • _**Each SPS shall have transfer_characteristics present and set equal to 18. This constrains the transfer characteristics to HLG as specified by Table 5 (Hybrid Log-Gamma (HLG) System Reference Non-Linear Transfer Functions) of ITU-R BT.2100 [23].**_
- • Each SPS shall have transfer_characteristics present and set equal to 18. This constrains the transfer characteristics to HLG as specified by Table 5 (Hybrid Log-Gamma (HLG) System Reference Non-Linear Transfer Functions) of ITU-R BT.2100 [23].
- • Each SPS shall have matrix_coeffs present and set equal to 9. This constrains the matrix coefficients to non-constant luminance Y′CbCr, as defined in ITU-R BT.2100 [23].
- • Each SPS shall have bit_depth_luma_minus8 and bit_depth_chroma_minus8 both set equal to 2. This constrains the bit depth to be 10 bits.
- • Each SPS shall have video_signal_type_present_flag set equal to 1 and video_full_range_flag set equal to 0. This constrains the sample values to be of narrow range. For more information regarding signal representation, see ITU-R BT.2100 [23], Table 9. Note that “narrow range” is sometimes referred to as “limited range.”
- • When Spatial Scalable Coding is used, the constraints of Section 6.3.1 shall apply.

This means that no backward-compatibility is used
