### ISSUE TITLE
[ATSC] Need reference to MPD Anchor

### ISSUE THREAD

**Issue by mikedo** [Dash-Industry-Forum/ATSC#52]
An API has been included in A/344 that allows a Broadcaster Application to control playback of on demand content through the Receiver Media Player using the MPD Anchor mechanism. (Refer to the A/344 Candidate Standard for definitions of the 'Broadcaster Application', 'Receiver Media Player' and the API used to play back on demand content.)

The MPD Anchor is defined in ISO 23009-1, extended in ISO 23009-1 Amd. 3, and it is discussed in the DASH IOP v4.0.  It is not mentioned in the ATSC 3.0 DASH IOP v1.0. 

A/344 would like to only normatively reference A/331 which, in turn, references the ATSC 3.0 DASH IOP v1.0. To allow A/344 to use the MPD Anchor, the ATSC 3.0 DASH IOP would be required to include a clause referencing the relevant syntax of the MPD Anchor from the appropriate standards or IOPs to avoid directly referencing the pertinent ISO 230091 Amd. 3.

Please add a clause to reference the MPD Anchor into the ATSC 3.0 DASH IOP.

**Comment by haudiobe** [comment]
Only needs an update on the reference chain. Mark/Mike will provide a change request.

**Comment by eyerm** [comment]
The ATSC-DASH-IF IoP should refer to the DASH-IF IoP v4.1 regarding how theDASH client starts playout, using MPD Anchor if provided.  I propose that a statement be added to Section 4.4 Client Recommendations: 
"The DASH Client should follow the guidelines in the DASH-IF IoP v4.1 regarding Section 4.3.4.4 Joining, Initial Buffering and Playout Recommendations, including starting playback at the MPD Anchor, if one is present.”

**Comment by haudiobe** [comment]
added to v1.03
