### ISSUE TITLE
[ATSC] Interactivity event support

### ISSUE THREAD

**Issue by mikedo** [Dash-Industry-Forum/ATSC#54]
[Background] ATSC 3.0 Application Signaling specifies mechanisms for signaling app-based enhancements in both linear services containing app-based enhancements and standalone app-based services (which consist entirely of app-based features), as well as mechanisms for delivering activation notifications, or “events” which activate or change the state of the associated applications at precise times in the media presentation timeline and can be mapped to wall-clock time. The details of application signaling are specified in A/337. Note that this section only deals with IF-1 of Figure 2, i.e. events as defined in A/337. Generic events may be used as well, and if so, they may be using IF-3 in Figure 2, as for example discussed in clause 6. Note also that the function “ATSC events” in Figure 2 may be part of the Application and therefore IF-1 and IF-3 coincide.
Some relevant features for event signaling are summarized. The format is expected to support signaling of events with precise timing such that the action of the triggered application operations can be synchronized. The format is expected to support signaling of a series of events. The format is expected to support signaling of events using the MPD as well as part of Media Segments of Representations, e.g., using the ‘emsg’ box [2]. Both broadcast- and broadband-delivered content may support events.

[Requirements] Interactivity Events may be carried:
-	As MPD Events as defined in ISO/IEC 23009-1, clause 5.10.2
-	As Inband events as defined in ISO/IEC 23009-1, clause 5.10.3 

CS A/337 is available here: https://www.atsc.org/wp-content/uploads/2017/01/A337S33-337r1Application-Signaling.pdf 

The basic intent is to move the  provisions of section 5.6 into the DASH-IF ATSC IOP v1.1 (and then remove them from A/337).

**Comment by haudiobe** [comment]
It is section 5.4, not 5.6! generally agreed, but needs text proposal for IOP

**Comment by mikedo** [comment]
Since this issues was filed: 1) the draft v1.1 IOP was updated; and 2) the text was removed from A/337 which was published in anticipation of v1.1 publishing "soon".
This issue can be closed.
