### ISSUE TITLE
HFR

### ISSUE THREAD

**Issue by haudiobe** [Dash-Industry-Forum/ATSC#55]
Submitter: Mickaël Raulet
Email: m.raulet@ateme.com
I have questions regarding HFR as it is in S34-1 specification. 
 
Is this prohibited for HFR to be deployed in a dual track approach?
•	A dual track approach would allow a service provider to easily switch from SFR to HFR without looking into the Elementary stream.
 
It may be more restrictive in the sense in the specification, is it prohibited for a service provider to dynamically change from SFR to HFR within a service?

Each temporal layer can be put in different DASH tracks, can’t it? Section 5.3.2.7 and 5.3.2.8 of http://dashif.org/wp-content/uploads/2017/02/DASH-IF-IOP-for-ATSC3-0-v1.0.pdf
 
<quote>
When temporal sub-layering is applied and all samples (for both TemporalId=0 and 1) are carried in a single track, the track shall contain sample group description box containing sample group entry type 'tscl' and corresponding sample to group box which as signs a sample group for each sample within that track.
<\quote>
 
It means both are possible – single and dual tracks. Is there another document that I shall refer to?

**Comment by haudiobe** [comment]
Takayashi will look into this

**Comment by mraulet** [comment]
bug in which sense? it has to a SINGLE track?

**Comment by haudiobe** [comment]
E-mail from Kazuhiko Takabayashi (ktaka) <Kazuhiko.Takabayashi@sony.com>, March 12 2018
--- begin ---
Putting two temporal video sub-streams in separate tracks is allowed.
See the last bullet in section 5.3.2.7 (in addition to the text in 5.3.2.8 you quoted) which describes the requirement applied in the case when temporal sub-layering with two temporal sub-layers is used in two Representations and each temporal sub-layer is carried in a Representation respectively.
Perhaps, adding the following text (note) after the paragraph starting at line 11 on page 26 (5.3.1) would help to clarify.
[proposed text for clarification] 
Two temporal sub streams can be carried either in a single track or two separate tracks.


[MR] It may be more restrictive in the sense in the specification, is it prohibited for a service provider to dynamically change from SFR to HFR within a service?

This question is beyond the scope of DASH-IF IOP for ATSC3.0.
The ATSC3.0 profile itself does not prohibit to dynamically change from SFR to HFR (or vice versa) at the Period boundary. However, if a service provider would like clients(players) to seamlessly transition across periods, requirements in the section 3.2.12 of DASH-IF IOPv4.0 (http://dashif.org/wp-content/uploads/2016/12/DASH-IF-IOP-v4.0-clean.pdf), which is referred to from the ATSC3.0 profile(section 3.2), should be considered and at least it is recommended to use "period-connectivity" that might disable such dynamic changes depending on track arrangements.

--- end ---
