### ISSUE TITLE
TOI field with $Time$ based addressing

### ISSUE THREAD

**Issue by TriveniSean** [Dash-Industry-Forum/ATSC#58]
The first bullet in section 4.2.2 reads:

_If $Number$ based addressing is used, the TOI field of a given ROUTE packet should be set to the $Number$ value of the DASH segment it contains..._

However, if $Time$ based addressing is used, what should be the TOI value?

**Comment by haudiobe** [comment]
Options:
- Use entity mode, but contradicts with A/331.
- Restrict time to 32 bit "somehow" => contradicts with DASH-IF IOP wher 64 bit are recommended
- Not use FileTemplate, but use FDT for each content location => it looks inefficient (is it really?)
- ALC allows the TOI field to be larger, but expected to break receivers
