### ISSUE TITLE
American Sign Language 

### ISSUE THREAD

**Issue by haudiobe** [Dash-Industry-Forum/ATSC#6]
Should video containing American Sign Language also be signaled in this way?

ATSC will address this issue

**Comment by haudiobe** [comment]
ATSC will provide input - sometime.

**Comment by mikedo** [comment]
ATSC TG3/S34-5 is working on a "Closed Signing" video track and its signaling.  Note that ASL is but one of many signing languages.  When that work is done, ATSC will communicate the output and requirements to DASH-IF.  I recommend this issue be closed.
